version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sdsetup-backend
    ports:
      - "5000:5000"
    volumes:
      - backend-config:/app/config
      - backend-files:/app/files
      - backend-temp:/app/temp
      - backend-updater:/app/updater
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped
    networks:
      - sdsetup-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.blazor
    container_name: sdsetup-frontend
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - SDSETUP_BACKEND_URL=${SDSETUP_BACKEND_URL:-http://localhost:5000}
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sdsetup-network

volumes:
  backend-config:
    driver: local
  backend-files:
    driver: local
  backend-temp:
    driver: local
  backend-updater:
    driver: local

networks:
  sdsetup-network:
    driver: bridge 